export const ANALYSIS_TEXT={
  en:{exportPreparing:'Preparing file…',exportError:'Could not prepare the file. Try exporting again.',exportReady:'File ready:',saveFile:'Save file',openFile:'Open file',exportHint:'If no download appears, tap Save file. On iPad, you can also open the file and use Share → Save to Files.',axes:'Plot variables',range:'Time range',rangeStart:'Start time (s)',rangeEnd:'End time (s)',showAll:'Show all',
    fit:'Fit model',interpretation:'What this fit means',moreHelp:'About the fit',appearance:'Graph appearance',export:'Export',
    angularFrequency:'Angular frequency',object:'Object',empty:'Add measurements in Tracker to see a graph.',
    unavailable:'A fit is not available for these variables and points. Check the selected range and choose another model.',
    positionLinear:'For position versus time, the slope represents constant velocity and the intercept is the fitted position at t = 0.',
    positionQuadratic:'For position versus time, this model can describe constant acceleration: acceleration = 2A, initial velocity = B, and position at t = 0 is C.',
    velocityLinear:'For velocity versus time, the slope represents constant acceleration and the intercept is the fitted velocity at t = 0.',
    linearHelp:'The slope describes how much the vertical quantity changes per unit of the horizontal quantity. The intercept is its fitted value at horizontal coordinate zero.',
    quadraticHelp:'A controls the quadratic term, B the linear term, and C the fitted value at horizontal coordinate zero. Their physical meaning depends on the selected axes.',
    sinusoidalHelp:'A is amplitude, B is angular frequency with respect to the horizontal variable, C is phase, and D is offset. For time on the horizontal axis, the period is 2π/B.',
    fitHelp:'The fit uses the plotted measurements within the selected time range. Time zero follows the experiment’s time setting. A model describes these data; it does not establish the underlying physical law.',
    r2Help:'R² describes how closely the fitted model follows the variation in the selected data. A high R² alone does not prove the model is appropriate.',
    measured:'Measurements',fitted:'Fitted curve'},
  es:{exportPreparing:'Preparando archivo…',exportError:'No se pudo preparar el archivo. Intenta exportar de nuevo.',exportReady:'Archivo listo:',saveFile:'Guardar archivo',openFile:'Abrir archivo',exportHint:'Si no aparece la descarga, toca Guardar archivo. En iPad también puedes abrir el archivo y usar Compartir → Guardar en Archivos.',axes:'Variables del gráfico',range:'Intervalo de tiempo',rangeStart:'Tiempo inicial (s)',rangeEnd:'Tiempo final (s)',showAll:'Mostrar todo',
    fit:'Modelo de ajuste',interpretation:'Qué significa este ajuste',moreHelp:'Acerca del ajuste',appearance:'Apariencia del gráfico',export:'Exportar',
    angularFrequency:'Frecuencia angular',object:'Objeto',empty:'Añade mediciones en Rastreador para ver un gráfico.',
    unavailable:'No hay un ajuste disponible para estas variables y puntos. Revisa el intervalo seleccionado y elige otro modelo.',
    positionLinear:'Para posición frente al tiempo, la pendiente representa una velocidad constante y la intersección es la posición ajustada en t = 0.',
    positionQuadratic:'Para posición frente al tiempo, este modelo puede describir aceleración constante: aceleración = 2A, velocidad inicial = B y posición en t = 0 igual a C.',
    velocityLinear:'Para velocidad frente al tiempo, la pendiente representa una aceleración constante y la intersección es la velocidad ajustada en t = 0.',
    linearHelp:'La pendiente describe cuánto cambia la magnitud vertical por unidad de la magnitud horizontal. La intersección es su valor ajustado en la coordenada horizontal cero.',
    quadraticHelp:'A controla el término cuadrático, B el término lineal y C el valor ajustado en la coordenada horizontal cero. Su significado físico depende de los ejes seleccionados.',
    sinusoidalHelp:'A es la amplitud, B la frecuencia angular respecto a la variable horizontal, C la fase y D el desplazamiento. Con tiempo en el eje horizontal, el período es 2π/B.',
    fitHelp:'El ajuste usa las mediciones graficadas dentro del intervalo de tiempo seleccionado. El tiempo cero sigue la configuración del experimento. Un modelo describe estos datos; no establece la ley física subyacente.',
    r2Help:'R² describe qué tan bien el modelo ajustado sigue la variación de los datos seleccionados. Un R² alto por sí solo no demuestra que el modelo sea adecuado.',
    measured:'Mediciones',fitted:'Curva ajustada'}
};
