export const GUIDE_TEXT = {
  en: {
    next: 'Suggested next action', pointsReady: 'Measurements available — review their accuracy',
    explain: 'Explain controls', explainHelp: 'Tap a toolbar icon to read its explanation, then choose its action. Tap Help again to leave this mode.',
    optionsHelp: 'Change language or theme, read about PhysTracker, or reset the experiment.',
    objectHelp: 'Choose which object to measure. Center of mass uses the measurements of both A and B.',
    videoView: 'Video workspace', videoViewHelp: 'Return to your video, image and measurement tools.',
    exportHelp: 'Download a project or open the graph export controls. Keep your original media separately.',
    title: 'Your experiment', open: 'Show guide', close: 'Hide guide', help: 'Quick help',
    steps: ['Media', 'Prepare', 'Measure', 'Analyze', 'Save & export'], complete: 'Ready',
    welcome: 'Start with a video or image', media: 'Open media', project: 'Open project',
    mediaHelp: 'Choose your own video or image. Opening new media starts a new experiment; save your current project first.',
    restore: 'Your measurements are restored. Open the original video or image to continue. Project files do not include media.',
    loading: 'Media is loading. Wait for the image or video frame to appear.',
    prepare: 'Check your time and distance measurements',
    prepareHelp: 'For motion in meters, set a known distance and position the axes. You can revisit these steps at any time.',
    fps: 'Frame rate', fpsHelp: 'This value is selected, not detected. Check the recording frame rate, especially for slow-motion video.',
    confirm: 'Confirm FPS', confirmed: 'FPS confirmed', scale: 'Set scale', axes: 'Position axes',
    calibrated: 'Distance calibrated', uncalibrated: 'Distance not calibrated', origin: 'Axes positioned',
    scaleHelp: 'Drag both ends of the green bar onto a known distance, then choose Enter Distance.',
    axesHelp: 'Drag the origin to set zero. Drag the rotation handle to align the axes.',
    measure: 'Choose how to measure', measureHelp: 'Choose Object A or B, then Manual or Automatic in the tracking menu. Automatic tracking needs a video and a distinctive feature with clear edges.',
    manualHelp: 'Click the same feature in each frame. Use Undo last point if you make a mistake.',
    automaticHelp: 'Select a distinctive feature, adjust the visible boxes, then choose Track one frame or Run tracking. Pause to adjust settings.',
    trackingMenu: 'Choose tracking mode', com: 'Center of mass is calculated from A and B. Track both objects at matching times.',
    analysis: 'Explore your measurements', analysisHelp: 'Choose graph variables and a data range, then try an appropriate curve fit. Inspect the measured points before drawing conclusions.',
    analyze: 'Open analysis', needData: 'Record points or enable a line profile to see data.', count: 'Recorded points',
    save: 'Keep your experiment', saveProject: 'Download project',
    saveHelp: 'Project JSON keeps measurements and settings. Keep the original media separately. Analysis offers PNG graphs and CSV motion data.',
    export: 'Open graph & export tools', saved: 'Saved in this browser', error: 'Browser save failed — download your project', idle: 'Local save available',
    storageHelp: 'Local saving belongs to this browser on this device. Download a project to keep a separate copy; media is not included.',
    light: 'Explore light intensity', lightHelp: 'Place the line across your image, choose a color channel and sampling width. Wavelength calibration is optional and needs two known references. Video FPS and motion scale are not required.',
    imageHelp: 'Images support manual measurements and line profiles. Automatic tracking needs a video. Open Spectroscopy & Line Profile in the settings to analyze light.',
    quickHelp: 'The toolbar controls tracking, scale and axes. Expand Overlay Tools for distances, angles and vectors, or Spectroscopy & Line Profile for light. Each guide step can be revisited.',
    loaded: 'Project opened. Choose its original video or image.', invalid: 'Could not open this project. Choose a valid PhysTracker JSON file.',
    reset: 'Delete this experiment and reset the app?', imageError: 'Could not load this image. Try another image file.',
    videoError: 'Could not load this video. Check the format or try another file.',
    doneDistance: 'Enter Distance', needMedia: 'Open media first',
  },
  es: {
    next: 'Siguiente acción sugerida', pointsReady: 'Mediciones disponibles: revisa su precisión',
    explain: 'Explicar controles', explainHelp: 'Toca un icono para leer su explicación y luego elige su acción. Toca Ayuda otra vez para salir de este modo.',
    optionsHelp: 'Cambia el idioma o tema, consulta información de PhysTracker o reinicia el experimento.',
    objectHelp: 'Elige el objeto que vas a medir. El centro de masa usa las mediciones de A y B.',
    videoView: 'Vista del video', videoViewHelp: 'Vuelve al video, la imagen y las herramientas de medición.',
    exportHelp: 'Descarga un proyecto o abre la exportación de gráficas. Conserva el archivo multimedia por separado.',
    title: 'Tu experimento', open: 'Mostrar guía', close: 'Ocultar guía', help: 'Ayuda rápida',
    steps: ['Archivo', 'Preparar', 'Medir', 'Analizar', 'Guardar y exportar'], complete: 'Listo',
    welcome: 'Comienza con un video o una imagen', media: 'Abrir video o imagen', project: 'Abrir proyecto',
    mediaHelp: 'Elige tu video o imagen. Abrir otro archivo inicia un experimento nuevo; guarda primero tu proyecto actual.',
    restore: 'Tus mediciones se han restaurado. Abre el video o la imagen original para continuar. Los proyectos no incluyen el archivo multimedia.',
    loading: 'Cargando el archivo. Espera a que aparezca la imagen o el fotograma.',
    prepare: 'Revisa las medidas de tiempo y distancia',
    prepareHelp: 'Para estudiar movimiento en metros, establece una distancia conocida y coloca los ejes. Puedes volver a estos pasos cuando quieras.',
    fps: 'Fotogramas por segundo', fpsHelp: 'Este valor es seleccionado, no detectado. Revisa la frecuencia de grabación, especialmente en cámara lenta.',
    confirm: 'Confirmar FPS', confirmed: 'FPS confirmados', scale: 'Establecer escala', axes: 'Colocar ejes',
    calibrated: 'Distancia calibrada', uncalibrated: 'Distancia sin calibrar', origin: 'Ejes colocados',
    scaleHelp: 'Arrastra los extremos de la barra verde sobre una distancia conocida y elige Introducir distancia.',
    axesHelp: 'Arrastra el origen para colocar el cero. Usa el control de rotación para orientar los ejes.',
    measure: 'Elige cómo medir', measureHelp: 'Elige el objeto A o B y luego Manual o Automático en el menú de seguimiento. El seguimiento automático requiere un video y un rasgo con bordes definidos.',
    manualHelp: 'Haz clic en el mismo rasgo en cada fotograma. Si te equivocas, usa Deshacer último punto.',
    automaticHelp: 'Selecciona un rasgo distintivo, ajusta los recuadros y elige Seguir un fotograma o Iniciar seguimiento. Pausa para ajustar las opciones.',
    trackingMenu: 'Elegir modo de seguimiento', com: 'El centro de masa se calcula con A y B. Sigue ambos objetos en los mismos instantes.',
    analysis: 'Explora tus mediciones', analysisHelp: 'Elige las variables y el intervalo de la gráfica; después prueba un ajuste adecuado. Revisa los puntos medidos antes de sacar conclusiones.',
    analyze: 'Abrir análisis', needData: 'Registra puntos o activa un perfil de línea para obtener datos.', count: 'Puntos registrados',
    save: 'Conserva tu experimento', saveProject: 'Descargar proyecto',
    saveHelp: 'El proyecto JSON conserva mediciones y ajustes. Guarda el archivo multimedia por separado. En Análisis puedes exportar gráficas PNG y datos de movimiento CSV.',
    export: 'Abrir gráficas y exportación', saved: 'Guardado en este navegador', error: 'Falló el guardado local: descarga tu proyecto', idle: 'Guardado local disponible',
    storageHelp: 'El guardado local pertenece a este navegador y dispositivo. Descarga un proyecto para conservar una copia; no incluye el video o la imagen.',
    light: 'Explora la intensidad de la luz', lightHelp: 'Coloca la línea sobre la imagen, elige un canal de color y un ancho de muestreo. La calibración de longitud de onda es opcional y requiere dos referencias conocidas. No se necesitan FPS ni escala de movimiento.',
    imageHelp: 'Las imágenes permiten mediciones manuales y perfiles de línea. El seguimiento automático requiere un video. Abre Espectroscopía y perfil de línea en los ajustes para analizar luz.',
    quickHelp: 'La barra controla seguimiento, escala y ejes. Abre Herramientas de superposición para distancias, ángulos y vectores, o Espectroscopía y perfil de línea para estudiar luz. Puedes volver a cada paso de la guía.',
    loaded: 'Proyecto abierto. Elige su video o imagen original.', invalid: 'No se pudo abrir el proyecto. Elige un archivo JSON válido de PhysTracker.',
    reset: '¿Eliminar este experimento y reiniciar la aplicación?', imageError: 'No se pudo cargar la imagen. Prueba otro archivo.',
    videoError: 'No se pudo cargar el video. Revisa el formato o prueba otro archivo.',
    doneDistance: 'Introducir distancia', needMedia: 'Abre primero un archivo',
  },
};
