import {referencePoints, validCalibration} from './spectroscopy.js';
export function calibrationFeedback(calibration,line) {
  if(validCalibration(calibration,line))return 'calibrated';
  const refs=referencePoints(calibration,line);
  for(let index=1;index<=2;index++) {
    if(!Number.isFinite(calibration?.[`p${index}_wl`]) || calibration[`p${index}_wl`]<=0)return `wavelength${index}`;
    if(!refs[index-1] || !Number.isFinite(refs[index-1].x) || !Number.isFinite(refs[index-1].y))return `position${index}`;
  }
  if(calibration.p1_wl===calibration.p2_wl)return 'differentWavelengths';
  return 'differentPositions';
}
export const SPECTRUM_WORKFLOW_TEXT={
  en:{sample:'Select spectrum',calibrate:'Calibrate wavelengths',explore:'Explore spectrum',draw:'Draw sampling line',replace:'Replace sampling line',drawHelp:'Click the start and end across the spectrum.',adjust:'Adjust sampling',next:'Next: calibrate wavelengths',purpose:'Know two spectral wavelengths? Mark them to display the graph in nanometers.',reposition:'Reposition',alignment:'Guide alignment',skip:'Continue in pixels',nextExplore:'Next: explore spectrum',view:'View spectrum',edit:'Edit sampling / calibration',compare:'Compare elements',export:'Export spectrum',calibrated:'Calibrated · Wavelength (nm)',pixels:'Uncalibrated · Position (px)',pixelChoice:'Position (px) · Wavelength calibration retained',wavelength1:'Enter a positive wavelength for Reference 1.',wavelength2:'Enter a positive wavelength for Reference 2.',position1:'Mark Reference 1 on the image.',position2:'Mark Reference 2 on the image.',differentWavelengths:'Enter two different wavelengths.',differentPositions:'Separate the reference positions across the guides, or adjust guide alignment.',needLine:'Open Adjust sampling line to place a line on the image.',waiting:'Waiting for image samples…',useWavelength:'Use wavelength calibration',widthHelp:'Averages pixels across the width of the sampling line. A wider band smooths variation but may include background.',channelHelp:'Brightness combines red, green and blue. Choose a color channel to inspect it separately.'},
  es:{sample:'Seleccionar espectro',calibrate:'Calibrar longitudes de onda',explore:'Explorar espectro',draw:'Dibujar línea de muestreo',replace:'Reemplazar línea de muestreo',drawHelp:'Haz clic en el inicio y el final a lo largo del espectro.',adjust:'Ajustar muestreo',next:'Siguiente: calibrar longitudes de onda',purpose:'¿Conoces dos longitudes de onda? Márcalas para mostrar la gráfica en nanómetros.',reposition:'Reposicionar',alignment:'Alinear guías',skip:'Continuar en píxeles',nextExplore:'Siguiente: explorar espectro',view:'Ver espectro',edit:'Editar muestreo / calibración',compare:'Comparar elementos',export:'Exportar espectro',calibrated:'Calibrado · Longitud de onda (nm)',pixels:'Sin calibrar · Posición (px)',pixelChoice:'Posición (px) · Calibración conservada',wavelength1:'Introduce una longitud de onda positiva para la Referencia 1.',wavelength2:'Introduce una longitud de onda positiva para la Referencia 2.',position1:'Marca la Referencia 1 en la imagen.',position2:'Marca la Referencia 2 en la imagen.',differentWavelengths:'Introduce dos longitudes de onda diferentes.',differentPositions:'Separa las referencias transversalmente a las guías o ajusta su inclinación.',needLine:'Abre Ajustar línea de muestreo para colocar una línea en la imagen.',waiting:'Esperando las muestras de la imagen…',useWavelength:'Usar calibración de longitud de onda',widthHelp:'Promedia los píxeles a lo ancho de la línea. Una banda más ancha suaviza las variaciones, pero puede incluir el fondo.',channelHelp:'El brillo combina rojo, verde y azul. Elige un canal de color para analizarlo por separado.'},
};

export function initialSamplingLine(dims) {
  if(!Number.isFinite(dims.w) || !Number.isFinite(dims.h) || dims.w<3 || dims.h<1)return null;
  return {p1:{x:dims.w*.2,y:(dims.h-1)/2},p2:{x:dims.w*.8,y:(dims.h-1)/2},spread:5,channel:'luma'};
}
export const SPECTRUM_PLACEMENT_TEXT={
 en:{purpose:'Enter the known wavelength of each reference, then locate its spectral line on the image.',locate:'Locate Reference {n} on image',locating:'Locating Reference {n}…',placed:'Reference {n} placed',instruction:'Click the spectral line corresponding to {value} nm (Reference {n}).',adjust:'Adjust sampling line',drag:'Drag the line onto your spectrum. Drag its endpoints to adjust its length and direction.',nextSample:'Calibration ready · Open Adjust sampling line next.',nextExplore:'Sampling line ready · Open Explore spectrum next.',skip:'No known wavelengths? Continue in pixels',missing:'Enter a positive wavelength above before locating this reference.'},
 es:{purpose:'Introduce la longitud de onda conocida de cada referencia y luego localiza su línea espectral en la imagen.',locate:'Localizar Referencia {n} en la imagen',locating:'Localizando Referencia {n}…',placed:'Referencia {n} colocada',instruction:'Haz clic en la línea espectral correspondiente a {value} nm (Referencia {n}).',adjust:'Ajustar línea de muestreo',drag:'Arrastra la línea sobre el espectro. Arrastra sus extremos para ajustar su longitud y dirección.',nextSample:'Calibración lista · Abre Ajustar línea de muestreo.',nextExplore:'Línea de muestreo lista · Abre Explorar espectro.',skip:'¿Sin longitudes de onda conocidas? Continuar en píxeles',missing:'Introduce arriba una longitud de onda positiva antes de localizar esta referencia.'},
};
